spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/dawproject
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
  logging:
    level:
      root: WARN
      es.proyecto.app: INFO
jwt:
  expiration: 3600000
