spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/dawproject
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
