spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/dawproject
    username: root
    password: 1234
    diverClassName: com.mysql.cj.jdbc.Driver
    # quitar lo de security enabled false cuando acabe de probar cosas.
    security:
      enabled: false;
  jpa:
    database:
      platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddlAuto: create