spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://localhost:3306/dawproject
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      org.hibernate: DEBUG
jwt:
  expiration: 3600000
