spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://192.168.1.34:3306/dawproject
    username: appuser
    password: securepassword

    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
  logging:
    level:
      root: WARN
      es.proyecto.app: INFO
jwt:
  expiration: 3600000
