openapi: 3.0.0
info:
  title: API de Gestión de Roles
  description: API para manejar roles en el sistema de productos de tatuajes.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Servidor local
paths:
  /roles:
    get:
      summary: Obtener todos los roles
      description: "Solo los usuarios con rol ADMIN pueden obtener todos los roles."
      operationId: getRoles
      tags:
        - Roles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: RoleResponse
                properties:
                  Roles:
                    type: array
                    description: Lista de roles
                    items:
                      $ref: "#/components/schemas/Role"

        '401':
          description: No autorizado (Unauthorized)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Acceso denegado (Forbidden)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /roles/{idRole}:
    put:
      summary: Actualizar un rol existente
      description: "Solo los usuarios con rol ADMIN pueden actualizar un rol."
      operationId: putRoleId
      tags:
        - Roles
      parameters:
        - in: path
          name: idRole
          required: true
          schema:
            type: string
          description: identificador del rol
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        '200':
          description: Rol actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Datos inválidos enviados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado (Unauthorized)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Acceso denegado (Forbidden)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Rol no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:

    Role:
      type: object
      properties:
        idRole:
          type: integer
          format: int32
          description: Identificador único del rol
        roleName:
          type: string
          description: Nombre del rol

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: Código del error
        errorMessage:
          type: string
          description: Descripción del error
security:
  - bearerAuth: []
